### ISSUE TITLE
Please provide LICENSE file

### ISSUE THREAD

**Issue by Mike-Crowe-BrightSign** [catchorg/Clara#24]
I've been trying to work out what license Clara is under. The "single-include" contains license text from clara_textflow.hpp:
```
// This work is licensed under the BSD 2-Clause license.
// See the accompanying LICENSE file, or the one at https://opensource.org/licenses/BSD-2-Clause
```

But I can't see a LICENSE file in the repository.

The separate clara.hpp contains no license information at all.

I suspect that Clara is also under the 2-clause BSD license, but I think this needs to be made completely clear.

Thanks.

Mike.

**Comment by aberghage** [comment]
This'd be helpful for me too — I'd like to contribute more, but it's hard to if I don't know the license I'm doing that under!

It looks like catch is under the boost license and textflow is bsd 2-clause, so I'd guess clara will wind up under one of those two as well, but it'd be great to have that spelled out someplace.

**Comment by philsquared** [comment]
Yes, it should be BSD-2 0 and I've now pushed a license file.
Sorry about that - I don't know how I missed it before!

I'm thinking of either moving Catch2 to BSD-2 as well, or Clara and TextFlow to Boost - so they're all on the same license. It's a bit confusing having them on different licenses (although, my understanding is, as the copyright holder I can relicense in this way).

**Comment by aberghage** [comment]
Thanks much, I appreciate it!

I'm obviously not a lawyer either, but AIUI that's right -- IIRC you can't revoke the old license for anyone who downloaded it when it was licensed that way, or something along those lines, but afaik you can change it at will going forward.

**Comment by philsquared** [comment]
I've gone with the easier option of relicensing Clara (and TextFlow) under Boost.
There have been no non-trivial contributions to either (you might argue that @horenmar has made non-trivial contributions to Clara, but he is definitely in agreement - although would be nice if he comment to that effect here so it's on the record :-) ).

Clara is now licensed under the Boost Software License.

**Comment by philsquared** [comment]
Thanks @horenmar - yes that was my reading, too - except there were quite a few (albeit infrastructural) commits by yourself - hence wanting your input here :-)

So I'm going to close this now.

**Comment by ronen-ufa** [comment]
For the record I agree my contribution was trivial :)

**Comment by philsquared** [comment]
Thanks @ronen - and, for the record, when we say "trivial" we don't mean "inconsequential" :-)

**Comment by ronen** [comment]
[redoing my comment it actually logged in to the correct account] 

For the record I agree my contribution was trivial :)

**Comment by philsquared** [comment]
Don't worry - it all worked out anyway (except now my reply precedes your comment - oh well!)

**Comment by BMBurstein** [comment]
Same here
