### ISSUE TITLE
Make second Argument of Args( int argc, char *argv[] ) const

### ISSUE THREAD

**Issue by red-angry-bird** [catchorg/Clara#64]
Hey there,

the second argument of clara::Args should be const because main(int, const char*[]) is conform to the standard.

**Comment by horenmar** [comment]
No, it does not. Only `int main(int, char**)` and `int main()` (and various spellings thereof) are standard conforming.

Also the current version of `Args::Args` has two overloads, one for init list of `std::string`s and `Args(int, char const* const*)`. Unlike `char const**`, `char const* const*` can accept arguments of type `char**`.

**Comment by red-angry-bird** [comment]
Thanks for your fast and particularized response
