### ISSUE TITLE
Contribution for docs/examples

### ISSUE THREAD

**Issue by edmBernard** [catchorg/Clara#67]
Hi @philsquared  
There is some issues about documentation and it's also add in the roadmap.
Did you need help on this point ?
Did you already have a table of content or a structure that we can complete ?
Did you prefer complete explanation of each functionnality or just a bunch of examples ?

related : https://github.com/catchorg/Clara/issues/49

**Comment by edmBernard** [comment]
I create these small examples inspired by your tests 
https://github.com/edmBernard/Clara/tree/master/docs/examples

**Comment by horenmar** [comment]
I looked through some of the examples and they look good (I did laugh a bit at `positive number must be between positive` though), but I am not really working on Clara -- I don't even have enough time for Catch2.
